kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "payment-pipeline"
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/hemelnj/payment.git'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/jenkinsFile
    type: JenkinsPipeline

    
    
    
    
    
    
    
    
    
    